[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_driver = "0.3.3"
bstr = "1.0.1"
nom = "7.1.3"
nom-supreme = "0.8.0"
once_cell = "1.16.0"
pathfinding = "4.0.0"

[dev-dependencies]
iai = "0.1.1"

[[bench]]
name = "benches"
harness = false
