#![feature(stdsimd)]
#![feature(array_chunks)]
#![feature(iter_array_chunks)]
#![feature(array_windows)]
#![feature(const_for)]
#![feature(const_option)]
#![feature(const_mut_refs)]
#![feature(const_slice_index)]
#![feature(unchecked_math)]
#![feature(unchecked_shifts)]
#![feature(byte_slice_trim_ascii)]
#![feature(portable_simd)]
#![feature(slice_pattern)]
#![feature(slice_split_at_unchecked)]
#![feature(maybe_uninit_uninit_array)]
#![feature(maybe_uninit_array_assume_init)]
#![allow(unused)]

pub mod helper;
pub mod solutions;
